steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'update', 'uk-gke-cec', '--zone', 'europe-west2-c', '--enable-master-authorized-networks', '--master-authorized-networks', '(dig +short myip.opendns.com @resolver1.opendns.com)']
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  id: 'Run deploy'
  args:
  - run
  - --filename=./manifests
  - --location=europe-west2-c
  - --cluster=uk-gke-cec
