steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - | 
    (curl checkip.amazonaws.com) && gcloud container clusters update uk-gke-cec --zone europe-west2-c --enable-master-authorized-networks --master-authorized-networks $_
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  id: 'Run deploy'
  args:
  - run
  - --filename=./manifests
  - --location=europe-west2-c
  - --cluster=uk-gke-cec
